/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#acc8f3",
        "tertiary-fixed-dim": "#c9c6be",
        "secondary-container": "#b7d3fe",
        "surface": "#f9f9f9",
        "inverse-primary": "#a8c8ff",
        "surface-variant": "#e2e2e2",
        "surface-container": "#eeeeee",
        "primary-fixed": "#d5e3ff",
        "background": "#f9f9f9",
        "primary": "#30578f", // Classic Luxury Deep Slate-Blue
        "outline-variant": "#c3c6d1",
        "on-primary-fixed": "#001b3c",
        "on-secondary-fixed-variant": "#2b486c",
        "on-surface-variant": "#434750",
        "surface-bright": "#f9f9f9",
        "secondary": "#446085",
        "on-tertiary-container": "#f6f3ea",
        "surface-container-lowest": "#ffffff",
        "primary-fixed-dim": "#a8c8ff",
        "on-background": "#1b1b1b",
        "inverse-on-surface": "#f1f1f1",
        "surface-container-highest": "#e2e2e2",
        "tertiary-container": "#706f68",
        "surface-tint": "#385f97",
        "secondary-fixed": "#d3e3ff",
        "on-error": "#ffffff",
        "inverse-surface": "#303030",
        "on-secondary-container": "#3f5b80",
        "on-primary-container": "#f0f3ff",
        "surface-container-high": "#e8e8e8",
        "tertiary-fixed": "#e5e2d9",
        "outline": "#737781",
        "surface-container-low": "#f3f3f3",
        "on-primary": "#ffffff",
        "error": "#ba1a1a",
        "on-secondary": "#ffffff",
        "surface-dim": "#dadada",
        "on-surface": "#1b1b1b",
        "on-tertiary-fixed-variant": "#484741",
        "on-secondary-fixed": "#001c39",
        "error-container": "#ffdad6",
        "tertiary": "#575750",
        "on-primary-fixed-variant": "#1c477d",
        "on-error-container": "#93000a",
        "on-tertiary-fixed": "#1c1c17",
        "primary-container": "#4a70a9",
        "on-tertiary": "#ffffff",
        "cream-bg": "#EFECE3"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin-mobile": "20px",
        "margin-desktop": "64px",
        "gutter-lg": "24px",
        "unit": "4px",
        "max-width": "1440px",
        "gutter-xs": "8px",
        "gutter-md": "16px"
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        serif: ["Outfit", "sans-serif"],
      },
    },
  },
  plugins: [],
}
