/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        neutral: {
          50: "#2A2020",
          100: "#2A2020",
          200: "#3D2F2F",
          300: "#4A3939",
          400: "#8A7979",
          500: "#A08E8E",
          600: "#C2B2B2",
          700: "#E0D9D9",
          800: "#E0D9D9",
          900: "#E0D9D9",
          950: "#FFFFFF",
        },
        "secondary-fixed-dim": "#acc8f3",
        "tertiary-fixed-dim": "#c9c6be",
        "secondary-container": "#2A2020",
        "surface": "#120E0E",
        "inverse-primary": "#a8c8ff",
        "surface-variant": "#2A2020",
        "surface-container": "#1C1515",
        "primary-fixed": "#d5e3ff",
        "background": "#120E0E",
        "primary": "#F3E4C9", // Soft Creamy Beige
        "outline-variant": "#3D2F2F",
        "on-primary-fixed": "#001b3c",
        "on-secondary-fixed-variant": "#2b486c",
        "on-surface-variant": "#E0D9D9",
        "surface-bright": "#2A2020",
        "secondary": "#432323", // Dark Maroon
        "on-tertiary-container": "#f6f3ea",
        "surface-container-lowest": "#120E0E",
        "primary-fixed-dim": "#a8c8ff",
        "on-background": "#E0D9D9",
        "inverse-on-surface": "#120E0E",
        "surface-container-highest": "#3D2F2F",
        "tertiary-container": "#706f68",
        "surface-tint": "#385f97",
        "secondary-fixed": "#d3e3ff",
        "on-error": "#ffffff",
        "inverse-surface": "#E0D9D9",
        "on-secondary-container": "#3f5b80",
        "on-primary-container": "#f0f3ff",
        "surface-container-high": "#2A2020",
        "tertiary-fixed": "#e5e2d9",
        "outline": "#8A7979",
        "surface-container-low": "#1C1515",
        "on-primary": "#ffffff",
        "error": "#ba1a1a",
        "on-secondary": "#ffffff",
        "surface-dim": "#1C1515",
        "on-surface": "#E0D9D9",
        "on-tertiary-fixed-variant": "#484741",
        "on-secondary-fixed": "#001c39",
        "error-container": "#ffdad6",
        "tertiary": "#2F5755",
        "on-primary-fixed-variant": "#1c477d",
        "on-error-container": "#93000a",
        "on-tertiary-fixed": "#1c1c17",
        "primary-container": "#4a70a9",
        "on-tertiary": "#ffffff",
        "cream-bg": "#120E0E"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin-mobile": "20px",
        "margin-desktop": "64px",
        "gutter-lg": "24px",
        "unit": "4px",
        "max-width": "1440px",
        "gutter-xs": "8px",
        "gutter-md": "16px"
      },
      fontFamily: {
        sans: ["-apple-system", "BlinkMacSystemFont", "Segoe UI", "Roboto", "Oxygen-Sans", "Ubuntu", "Cantarell", "Fira Sans", "Droid Sans", "Helvetica Neue", "Helvetica", "Arial", "sans-serif"],
        serif: ["-apple-system", "BlinkMacSystemFont", "Segoe UI", "Roboto", "Oxygen-Sans", "Ubuntu", "Cantarell", "Fira Sans", "Droid Sans", "Helvetica Neue", "Helvetica", "Arial", "sans-serif"],
      },
    },
  },
  plugins: [],
}
